/**
 * @name CommonLoggerConstants.cls
 * @description common constants for CommonLogger
 */
public without sharing class CommonLoggerConstants {
  public static final Integer MAX_WIDTH = 3000;
  public static final String LOGGER_DEFAULT = 'DEFAULT';
  public static final String PARTING_LINE = '------------------------------';
  public static final String SYMBOL_CLS = '.cls';
  public static final String TIMEZONE_JST = 'Asia/Tokyo';
  public static final String DATE_FORMAT = CommonConstants.DATE_FORMAT;
  public static final String SYMBOL_DIVIDER = CommonConstants.SYMBOL_DIVIDER;
  public static final String SYMBOL_NEWLINE = CommonConstants.SYMBOL_NEWLINE;
}
