/**
 * @name FAT_CommonLoggerConstants.cls
 * @description common constants for FAT_CommonLogger
 */
public without sharing class FAT_CommonLoggerConstants {
  public static final Integer MAX_WIDTH = 3000;
  public static final String FIELD_RECORD_TYPE_ID = 'RecordTypeId';
  public static final String LOGGER_DEFAULT = 'DEFAULT';
  public static final String SYMBOL_CLS = '.cls';
  public static final String TIMEZONE_JST = 'Asia/Tokyo';
  public static final String DATE_FORMAT = FAT_CommonConstants.DATE_FORMAT;
  public static final String SYMBOL_DIVIDER = FAT_CommonConstants.SYMBOL_DIVIDER;
  public static final String SYMBOL_NEWLINE = FAT_CommonConstants.SYMBOL_NEWLINE;
}
